name: Deploy

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          ping: ${{ secrets.DEPLOY_HOST }}

      - name: SSH actions
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            if [ -d boistressbot ]; then
              cd boistressbot
              docker compose down -v
              cd ..
            fi

            rm -rf ~/${{ github.event.repository.name }}
            git clone git@github.com:${{ github.repository }}.git

            cd ${{ github.event.repository.name }}
            touch .env
            echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN}} >> .env
            echo GUILD_ID=${{ secrets.GUILD_ID}} >> .env
            echo CREATOR_DISCORD_ID=${{ secrets.CREATOR_DISCORD_ID}} >> .env
            echo CREATOR_STEAM_ID=${{ secrets.CREATOR_STEAM_ID}} >> .env
            echo STEAM_API_KEY=${{ secrets.STEAM_API_KEY}} >> .env
            echo GENERAL_CHANNEL_ID=${{ secrets.GENERAL_CHANNEL_ID}} >> .env
            echo BOT_COMMANDS_CHANNEL_ID=${{ secrets.BOT_COMMANDS_CHANNEL_ID}} >> .env

            docker compose up -d
